# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'Slocan' do
  pod 'MDCSwipeToChoose', :git => 'https://github.com/modocache/MDCSwipeToChoose.git'
  pod 'AFNetworking'
  pod 'SVProgressHUD'
end

target 'UnitTests' do

end

